### ISSUE TITLE
reproduction

### ISSUE THREAD

**Issue by drom** [Ttl/vna2#2]
Hi Henrik,
I am impressed by your VNA design, and want to made one for myself.
Do you recommend any improvements over what you have on Github?
You mentioned:
> The board had unfortunate resonance at 4.2 GHz, which I think comes from the poor grounding of the multiple ground planes. I think I'll need to order a new PCB with better grounding.

Do you plan making new revision of the PCB?

**Comment by Ttl** [comment]
Better isolation is the biggest one. Source needs to be shielded and the whole thing needs a case. 5V rail should also have LDO after the buck converter to clean switching noise.

I'm not planning to make a version of the VNA at the moment. Maybe someday in future when I have motivation, but this version works fine enough for now.

The resonance refers to the TRL test board not VNA PCB. I have already made a new version of the test board which works fine.

**Comment by jsr38** [comment]
Hey @drom  - I was thinking of building one too.  Sounds like straightforward changes.  I'm not planning on doing it right now but in a few months, when I get some time and my test gear back.  It would be good to share any design changes and progress.

**Comment by ReinierG** [comment]
Same here. Time is the biggest issue. I would like to join you. I don't 
mind the extra cost of better components (switches, shielding cans, 
wider range VCO, ...)


Op 24-7-2017 om 22:45 schreef Jeremy Reeve:

**Comment by oe2lsp** [comment]
that’s really great :)
I'm planing to build one as well. For shielding maybe for testing a simple Cu-FR4 shield is enough.
There are two improvements I'm thinking about, the first one is a shield around the generator at the top right. As well as some additional vias. I don't know if it is possible to hide a 5V LDO in the current shape, this would be nice so that everyone can use the same milled shield, if we find one.

**Comment by drom** [comment]
Great to hear that I am not alone.
@Ttl agree that extra LDO is good.
@Ttl @oe2lsp I am all for more ground, more vias, Cu shielding. Don't mind bigger total PCB area, bit with better ground.
Milled RF shield, sound's expensive, but designing common bended RF shield sounds great

**Comment by Ttl** [comment]
Similar sheet metal shielding as with the receiver is not really good enough unless it is soldered all the way such that there are absolutely no gaps at all but that makes prototyping very hard. Of course any shield is better than nothing, but even -100 dB leakage can be detect and a shield with gaps radiates better than that.

I was thinking of separating source and receiver to their own PCBs and connecting the RF with SMA cables. Physical separation is good for improving isolation. Unfortunately all the separate PCBs, shielding, cases and connectors really increase the cost, which is why I haven't had the motivation to make a new version yet.

Also some other improvements that I had in mind:

* Make IF amplifier gain variable (at least 20 dB). Amplifier gain drops at high frequencies and the signal power is much smaller than at low frequencies. Because of that ADC range is not utilized fully and the dynamic range is smaller.
* Replace ADA4932-1 IF amplifier with for example ADA4940-1. The current amplifier doesn't have rail-to-rail outputs and at the maximum output voltage it's close to the limit and causes distortion.
* Duplicate the receivers. One receiver for each port to improve the isolation. This also doubles the measurement speed.

**Comment by vrytikov** [comment]
This is a great project. I am thinking of building one too. Would be nice to get pcb improvement.

**Comment by ReinierG** [comment]
Hi Henrik,

What about using the recently introduced LMX2594? It has a 10 MHz- 15 
GHz range and integrated LDOs. It will be difficult to make good 
calibration standards. I've never had a use case for frequencies above 
2.4 GHz, but the improved time domain transformation resolution would be 
a big plus.
I agree with you about separating parts and connecting with SMA cables. 
Modular design make things easier to make improvements. That's how I 
started my VNA design (and did not yet finish it...)


Op 25-7-2017 om 07:24 schreef Henrik Forstén:

**Comment by Ttl** [comment]
There are some issues with using LMX2594. First is that the chip costs 56€ compared to just 10€ for MAX2871. Second is that amplifier, switches and mixer needs to be replaced with 10 GHz capable ones. Those are going to cost also much more than the current ones. Total cost for 10 GHz version would be more than twice of the current version.

**Comment by drom** [comment]
@Ttl agree, changing to LMX2594 (15GHz, $63) or even LMX2592 (10GHz, $35) will drive the rest of BOM up.

**Comment by drom** [comment]
@Ttl how about replacing monster BGA FPGA package with something like Lattice IC40 Ultra Plus (in 48QFN package): file:///home/drom/work/github/drom/iCE40%20UltraPlus%20Family%20Data%20Sheet.pdf
It has 39 IO, 1Mibit SRAM, 8 MULT16,... etc.

**Comment by Ttl** [comment]
ICE40 might have enough gates, but 39 IO pins is not enough. At least 60 pins are needed.

**Comment by jsr38** [comment]
Perhaps if there is sufficient demand/activity there is a case for creating individual tickets concerning each proposed change or improvement.  Perhaps there is even a case for a cut-down version and a version where cost is less of a constraint.  Maybe that's a separate project altogether.

On the topic of shielding, would a milled shield be better for prototyping activities?  I don't have practical experience of such things but intuition tells me one should be able to remove and replace such a shield a large number of times if it were bolted.  I guess that would also require something like a fingerstrip to make good contiguous contact with the ground-plane on the board.  Although it sounds expensive perhaps prototyping of the shield could be done with a hobby 3d printer to validate the design before sending the job to a machinist then if there is sufficient interest split the cost of multiple shields to amortise the setup cost.

Actually, over the next few months I am working on modelling the properties of thermoplastic coated with graphite and then electroplated.  Maybe it's good enough to use for prototyping the shielding proper.  Maybe not.

**Comment by MichaelRColton** [comment]
Hi there! I'm another guy that's extremely interested in reproducing (and contributing to) this project. Looks like I can get the main PCB from jlcpcb.com for about $45 for 10 Pcs, gold plated. Does anyone know about how much the rest of the components cost? Or better yet, does anyone have a digikey/mouser/octopart BOM put together?

Regarding machining an enclosure/shield. In my experience, it's not as expensive or as hard as you guys seem to fear. I had  a run of custom milled cases and knobs made for a project of mine (here's how they turned out: https://www.kickstarter.com/projects/1703258614/psdr-pocket-hf-sdr-transceiver-with-vna-and-gps/posts/1643428 ) those ended up being about $25.

In addition, I have access to a CNC milling machine myself, so for prototyping and small runs, say, for you guys here, I could just run them myself.

With KiCad's ability to export fairly accurate 3D models of boards, designing the shield/enclosure wouldn't be too hard. And I agree with jsr38 that 3D printing to check fit is worth doing. Ideally the board would be redesigned with an enclosure in mind (more space between sub-circuits, clearings in the soldermask for the shield to make contact, more mounting holes, etc.) but I think something could be fit around the existing design. If nothing else, I would imagine it would take some of the environmental sensitivity out of the current design.

**Comment by kapil-iitk** [comment]
I have few to suggestions,
1. Integrate the coupler within the VNA PCB to save few bucks from 6+ 6=12 SMA connectors, and cables.
2. Use copper tape for the shilding. Also add insulator patch (such as OHP sheet) above the circuit (to isolate from the DC short). This may be efficient for the prototyping.

3. Any alternate of FPGA? to reduce the complexity and assembling inaccuracy.

**Comment by blackberryer** [comment]
Hi Henrik,
You mentioned:
The resonance refers to the TRL test board not VNA PCB. I have already made a new version of the test board which works fine.

I guess your first version of the TRL test board didn't have enough vias. Is your new board improved grounding by punching enough holes?Is there any improvement elsewhere?
