### ISSUE TITLE
I and Q data to S parameters algorithm

### ISSUE THREAD

**Issue by vijaykarthik123** [Ttl/vna2#5]
Hi Henrik,

Great job on the VNA design! I am trying to correlate between an FMCW radar and a VNA. In the FMCW radar, the ADC digitizes the IF signal into I and Q samples.

In your VNA design, the ADC samples the IF signal into I and Q samples. How did you convert the low frequency IF data into RF S parameters? I am reading your `sparam.py` file and in `iq_to_sparam()` there is a formula and algorithm which I am not able to grasp.

Thanks for your help on this.

**Comment by Ttl** [comment]
VNA mixes the RF to low frequency IF (few MHz) which is sampled by the ADC and is then IQ mixed inside the FPGA in the digital domain. It needs to be done digitally because analog IQ mixing accuracy isn't high enough.

S-parameters from IQ samples is just normal ratios from the S-parameter definitions. For example S11 is reflected power measurement divided by transmitted power measurement. `sw_correction` in `iq_to_sparam()` is switch correction. It's a part of 8-term VNA calibration.
